### ISSUE TITLE
change todo's font size 

### ISSUE THREAD

**Issue by DannyDies** [delashum/obsidian-checklist-plugin#13]
hey, how to change todo's font size? They're too large for me and I can't find way to do it.

**Comment by delashum** [comment]
I don't prescribe any specific font-size to the todo's, so you if you adjusted the font-size of the entire app (default is 16px I believe) that should do it. Would that work? If not, how would you prefer to control the font-size?

**Comment by DannyDies** [comment]
![1](https://user-images.githubusercontent.com/70198933/106926883-9f0e5e00-6722-11eb-85eb-887345337f45.PNG)
Isn`' working. Changing size influence only on page name(red zone on image). I'd found font size in main js code = 16px and it is only changing only page reference(not a todo itself). 
i'd like to change todo's pretty close to my tag size.

**Comment by Tweetyblue** [comment]
Hi, have you found a way to change the font size of the todo's ?

**Comment by vishae** [comment]
I'm also interested in this

**Comment by krivaten** [comment]
Hey y'all. I'm gonna try to work on a this over the next couple days to help out, using CSS variables/custom properties. In the meantime, you _should_ be able to do something like the following in your `obsidian.css` file:

```css
// Change header font-size
.todo-list .group-header {
    font-size: 20px;
}

// Change task font-size
.todo-list .item {
    font-size: 12px;
}
```
